version: '3.1'

services:
  postgres:
    image: postgres
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "talco"

  web:
    build: ./
    image: talco
    container_name: talco
    restart: always
    ports:
      - "8082:5000"
    volumes:
      - /storage/ccmmma/prometeo/data/opendap:/storage/ccmmma/prometeo/data/opendap
    depends_on:
      - postgres

volumes:
  postgres_data: